name: LoginLogger
main: com.wizardlybump17.loginlogger.LoginLoggerPlugin
version: "${project.version}"
author: WizardlyBump17
api-version: 1.17
libraries:
  - com.j256.ormlite:ormlite-core:5.6
  - com.j256.ormlite:ormlite-jdbc:5.6